name: flutter_wowza
description: Flutter WOWZA plugin for iOS/Android. The project is based on Wowza GoCoder SDK
homepage: https://github.com/matifdeveloper/flutter-wowza
version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.namit.flutter_wowza
    pluginClass: FlutterWowzaPlugin